helfi_hakuvahti.config.*:
  type: config_entity
  label: 'Hakuvahti configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    site_id:
      type: string
      label: 'Site ID'

helfi_hakuvahti.settings:
  type: config_object
  label: 'Helfi hakuvahti settings'
  mapping:
    api_key:
      type: string
    base_url:
      type: string

    hakuvahti_tos_checkbox_label:
      type: label
      label: 'Hakuvahti terms of service checkbox label'
      translatable: true
    hakuvahti_tos_link_text:
      type: label
      label: 'Hakuvahti terms of service link text'
      translatable: true
    hakuvahti_tos_link_url:
      type: label
      label: 'Hakuvahti terms of service URL'
      translatable: true
    hakuvahti_instructions_link_url:
      type: label
      label: 'Hakuvahti detailed instructions link URL'
      translatable: true

